# Generated by Django 5.0.6 on 2025-10-08 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_suggestion_upvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='upvote',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
