# Generated by Django 5.0.6 on 2025-10-21 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_remove_suggestion_upvote_comment_upvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvote_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
